# Generated by Django 4.2.7 on 2023-11-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.BigIntegerField(blank=True, default=None, null=True)),
                ('intensity', models.BigIntegerField(blank=True, default=None, null=True)),
                ('sector', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('insight', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=500)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('start_year', models.BigIntegerField(blank=True, default=None, null=True)),
                ('impact', models.BigIntegerField(blank=True, default=None, null=True)),
                ('added', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('published', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('relevance', models.BigIntegerField(blank=True, default=None, null=True)),
                ('pestle', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('likelihood', models.BigIntegerField(blank=True, default=None, null=True)),
                ('City', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
